name: 'Build Source Code'
description: 'use the action to build source code'
inputs:
  jar_version:  # id of input
    description: 'jar version'
    required: true
    default: '0.0.1-snapshot'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'
  
  steps:
    - uses: actions/checkout@v3
      with:
        path: ${{ steps.uppercase.outputs.uppercase_account }}
    
    using: 'zx'
    main: 'build-source-code.mjs'
    
    - name: Build source code
      id: build-source-code
      run: |
        cd ${{ steps.env.outputs.USER_WORK_SPACE_PATH }}
        #modify maven package version
        mvn versions:set -DnewVersion=${{ github.event.inputs.JAR_VERSION }} -s settings.xml
        #maven package
        mvn clean package -U -s settings.xml
