name: 'Build Source Code'
description: 'use the action to build source code'
inputs:
  jar_version:  # id of input
    description: 'jar version'
    required: true
    default: '0.0.1-snapshot'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'
  
  steps:
    - uses: actions/checkout@v3
      with:
        path: ${{ steps.uppercase.outputs.uppercase_account }}
        
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    using: 'zx'
    main: 'build-source-code.mjs'
        
